const FETCH_WORDLIST = 'FETCH-WORDLIST';
const ADD_WORD = 'ADD-WORD';
const DELETE_WORD = 'DELETE-POST';
const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const UPDATE_WORD = "UPDATE_WORD";
const USER_LOADED = 'USER_LOADED';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAIL = 'LOGIN_FAIL';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAIL = 'REGISTER_FAIL';
const AUTH_ERROR = 'AUTH_ERROR';
const GET_ERRORS = 'GET_ERRORS';
const CLEAR_ERRORS = 'CLEAR_ERRORS';
const CREATE_USER = 'CREATE_USER';
const GET_USERS = 'GET_USERS'
const UPDATE_USER = 'UPDATE_USER'

const DELETE_EVENT = 'DELETE_EVENT';
const ADD_EVENT = 'ADD_EVENT';
const GET_EVENTS = 'GET_EVENTS';


const ADD_MESSAGE = 'ADD_MESSAGE';
const UPDATE_AUTH = 'UPDATE_AUTH';
const GET_MSGS = 'GET_MSGS'


export {
    UPDATE_USER, GET_USERS, CREATE_USER, CLEAR_ERRORS, GET_ERRORS, UPDATE_WORD,
    FETCH_WORDLIST, ADD_WORD, DELETE_WORD, LOGIN, LOGOUT, AUTH_ERROR, LOGIN_FAIL,
    LOGIN_SUCCESS, ADD_EVENT, GET_EVENTS, USER_LOADED, REGISTER_FAIL, REGISTER_SUCCESS,
    UPDATE_AUTH, ADD_MESSAGE, GET_MSGS, DELETE_EVENT
};